# Generated by Django 3.1.7 on 2021-02-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20210226_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start',
            new_name='start_time',
        ),
    ]
