# Generated by Django 3.1.7 on 2021-03-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20210226_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default='Vaisselle', max_length=50),
            preserve_default=False,
        ),
    ]
