# Generated by Django 3.1.7 on 2021-03-02 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0005_task_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.home')),
            ],
            options={
                'verbose_name': 'HomeTasks',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='home_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.hometask'),
        ),
    ]
