# Generated by Django 3.1.7 on 2021-03-04 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planning', '0006_auto_20210302_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometask',
            name='difficulty',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='homes',
            field=models.ManyToManyField(to='planning.Home'),
        ),
        migrations.AlterField(
            model_name='hometask',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
