# Generated by Django 3.1.7 on 2021-03-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_auto_20210305_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hometask',
            options={'verbose_name': 'HomeTask', 'verbose_name_plural': 'HomeTasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
