# Generated by Django 3.1.7 on 2021-04-10 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='spent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.spent'),
        ),
    ]
