# Generated by Django 3.1.7 on 2021-04-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_task_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.profile'),
        ),
    ]
