# Generated by Django 3.1.7 on 2021-04-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_auto_20210410_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='denonceur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denonceur', to='planning.profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='doer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doer', to='planning.profile'),
        ),
    ]
